import re

from DotPlot import DotPlot
from FastaParser import FastaParser
from FastaReader import FastaReader
from GlobalMatch import GlobalMatch
from LocalMatch import LocalMatch
from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QFileDialog


class Ui_MainWindow(object):
    """
            A class used to show GUI. User have three options to provide sequence: by hand, from file, from web.
            When one option is selected with combobox, other are disabled.

            On "Show charts" button two plots show, one is 'base', next is filtered with given parameters of window
            and treshold.


            """

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(888, 778)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 841, 361))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.open_file_button_1 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.open_file_button_1.setObjectName("open_file_button_1")
        self.verticalLayout.addWidget(self.open_file_button_1)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.sequence_1_txt = QtWidgets.QTextEdit(self.horizontalLayoutWidget)
        self.sequence_1_txt.setObjectName("sequence_1_txt")
        self.verticalLayout.addWidget(self.sequence_1_txt)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.id_1_txt = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.id_1_txt.setObjectName("id_1_txt")
        self.verticalLayout.addWidget(self.id_1_txt)
        self.search_1 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.search_1.setObjectName("search_1")
        self.verticalLayout.addWidget(self.search_1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox_2)
        self.open_file_button_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.open_file_button_2.setObjectName("open_file_button_2")
        self.verticalLayout_3.addWidget(self.open_file_button_2)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.sequence_2_txt = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget)
        self.sequence_2_txt.setObjectName("sequence_2_txt")
        self.verticalLayout_3.addWidget(self.sequence_2_txt)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.id_2_txt = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.id_2_txt.setObjectName("id_2_txt")
        self.verticalLayout_3.addWidget(self.id_2_txt)
        self.search_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.search_2.setObjectName("search_2")
        self.verticalLayout_3.addWidget(self.search_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.statistics_txt = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.statistics_txt.setEnabled(True)
        self.statistics_txt.setReadOnly(True)
        self.statistics_txt.setGeometry(QtCore.QRect(560, 400, 281, 341))
        self.statistics_txt.setObjectName("statistics_txt")
        self.matchModeTab = QtWidgets.QTabWidget(self.centralwidget)
        self.matchModeTab.setGeometry(QtCore.QRect(10, 410, 541, 301))
        self.matchModeTab.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(420, 10, 116, 221))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.gap_txt_lm = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.gap_txt_lm.setMinimum(-100)
        self.gap_txt_lm.setMaximum(100)
        self.gap_txt_lm.setProperty("value", -2)
        self.gap_txt_lm.setObjectName("gap_txt_2")
        self.verticalLayout_5.addWidget(self.gap_txt_lm)
        self.label_15 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_5.addWidget(self.label_15)
        self.G_txt_lm = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.G_txt_lm.setMinimum(-100)
        self.G_txt_lm.setMaximum(100)
        self.G_txt_lm.setProperty("value", -15)
        self.G_txt_lm.setObjectName("G_txt_2")
        self.verticalLayout_5.addWidget(self.G_txt_lm)
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_5.addWidget(self.label_16)
        self.L_txt_lm = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.L_txt_lm.setMinimum(-100)
        self.L_txt_lm.setMaximum(100)
        self.L_txt_lm.setProperty("value", -2)
        self.L_txt_lm.setObjectName("spinBox_3")
        self.verticalLayout_5.addWidget(self.L_txt_lm)
        self.substitution_matrix = QtWidgets.QTableWidget(self.tab)
        self.substitution_matrix.setGeometry(QtCore.QRect(0, 40, 411, 151))
        self.substitution_matrix.setObjectName("substitution_matrix")
        self.substitution_matrix.setColumnCount(4)
        self.substitution_matrix.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.substitution_matrix.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.substitution_matrix.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.substitution_matrix.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.substitution_matrix.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.substitution_matrix.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.substitution_matrix.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.substitution_matrix.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.substitution_matrix.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.substitution_matrix.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.substitution_matrix.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.substitution_matrix.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.substitution_matrix.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.substitution_matrix.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.substitution_matrix.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.substitution_matrix.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.substitution_matrix.setItem(1, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.substitution_matrix.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.substitution_matrix.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.substitution_matrix.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.substitution_matrix.setItem(2, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.substitution_matrix.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.substitution_matrix.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.substitution_matrix.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.substitution_matrix.setItem(3, 3, item)
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(0, 20, 161, 17))
        self.label_7.setObjectName("label_7")
        self.match_option_cbox = QtWidgets.QComboBox(self.tab)
        self.match_option_cbox.setGeometry(QtCore.QRect(0, 200, 411, 25))
        self.match_option_cbox.setObjectName("match_option_cbox")
        self.match_option_cbox.addItem("")
        self.match_option_cbox.addItem("")
        self.path_nr_combobox = QtWidgets.QComboBox(self.tab)
        self.path_nr_combobox.setGeometry(QtCore.QRect(90, 230, 131, 25))
        self.path_nr_combobox.setObjectName("path_nr_combobox")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(10, 230, 67, 20))
        self.label_12.setObjectName("label_12")
        self.matchModeTab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(30, 20, 481, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_6.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_6.addWidget(self.label_18)
        self.gap_txt_gm = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.gap_txt_gm.setMinimum(-100)
        self.gap_txt_gm.setMaximum(100)
        self.gap_txt_gm.setProperty("value", -2)
        self.gap_txt_gm.setObjectName("gap_txt_gm")
        self.verticalLayout_6.addWidget(self.gap_txt_gm)
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_6.addWidget(self.label_19)
        self.match_txt_gm = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.match_txt_gm.setMinimum(-100)
        self.match_txt_gm.setMaximum(100)
        self.match_txt_gm.setProperty("value", 1)
        self.match_txt_gm.setObjectName("match_txt_gm")
        self.verticalLayout_6.addWidget(self.match_txt_gm)
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_6.addWidget(self.label_20)
        self.mismatch_txt_gm = QtWidgets.QSpinBox(self.verticalLayoutWidget_2)
        self.mismatch_txt_gm.setMinimum(-100)
        self.mismatch_txt_gm.setMaximum(100)
        self.mismatch_txt_gm.setProperty("value", -1)
        self.mismatch_txt_gm.setObjectName("mismatch_txt_gm")
        self.verticalLayout_6.addWidget(self.mismatch_txt_gm)
        self.matchModeTab.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(30, 20, 221, 221))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_21 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_7.addWidget(self.label_21)
        self.label_22 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_7.addWidget(self.label_22)
        self.gap_txt_dp = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.gap_txt_dp.setMinimum(-100)
        self.gap_txt_dp.setMaximum(100)
        self.gap_txt_dp.setProperty("value", -2)
        self.gap_txt_dp.setObjectName("gap_txt_dp")
        self.verticalLayout_7.addWidget(self.gap_txt_dp)
        self.label_23 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_7.addWidget(self.label_23)
        self.match_txt_dp = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.match_txt_dp.setMinimum(-100)
        self.match_txt_dp.setMaximum(100)
        self.match_txt_dp.setProperty("value", 1)
        self.match_txt_dp.setObjectName("match_txt_dp")
        self.verticalLayout_7.addWidget(self.match_txt_dp)
        self.label_24 = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_7.addWidget(self.label_24)
        self.mismatch_txt_dp = QtWidgets.QSpinBox(self.verticalLayoutWidget_3)
        self.mismatch_txt_dp.setMinimum(-100)
        self.mismatch_txt_dp.setMaximum(100)
        self.mismatch_txt_dp.setProperty("value", -1)
        self.mismatch_txt_dp.setObjectName("mismatch_txt_gm_2")
        self.verticalLayout_7.addWidget(self.mismatch_txt_dp)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(280, 20, 201, 129))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_26 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_10.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_10.addWidget(self.label_27)
        self.window_txt_dp = QtWidgets.QSpinBox(self.verticalLayoutWidget_4)
        self.window_txt_dp.setMinimum(0)
        self.window_txt_dp.setMaximum(100)
        self.window_txt_dp.setProperty("value", 15)
        self.window_txt_dp.setObjectName("window_txt_dp")
        self.verticalLayout_10.addWidget(self.window_txt_dp)
        self.label_28 = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_10.addWidget(self.label_28)
        self.error_txt_dp = QtWidgets.QSpinBox(self.verticalLayoutWidget_4)
        self.error_txt_dp.setMinimum(0)
        self.error_txt_dp.setMaximum(100)
        self.error_txt_dp.setProperty("value", 5)
        self.error_txt_dp.setObjectName("error_txt_dp")
        self.verticalLayout_10.addWidget(self.error_txt_dp)
        self.matchModeTab.addTab(self.tab_3, "")
        self.show_match_button = QtWidgets.QPushButton(self.centralwidget)
        self.show_match_button.setGeometry(QtCore.QRect(320, 380, 219, 31))
        self.show_match_button.setObjectName("show_global_match_button_2")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(570, 380, 67, 17))
        self.label_25.setObjectName("label_25")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.matchModeTab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "First sequence:"))
        self.comboBox.setItemText(0, _translate("MainWindow", "User input"))
        self.comboBox.setItemText(1, _translate("MainWindow", "From File"))
        self.comboBox.setItemText(2, _translate("MainWindow", "From web"))
        self.open_file_button_1.setText(_translate("MainWindow", "Open file"))
        self.label_4.setText(_translate("MainWindow", "sequence:"))
        self.label_3.setText(_translate("MainWindow", "id:"))
        self.search_1.setText(_translate("MainWindow", "Search"))
        self.label_2.setText(_translate("MainWindow", "Second sequence:"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "User input"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "From File"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "From web"))
        self.open_file_button_2.setText(_translate("MainWindow", "Open file"))
        self.label_6.setText(_translate("MainWindow", "sequence:"))
        self.label_5.setText(_translate("MainWindow", "id"))
        self.search_2.setText(_translate("MainWindow", "Search"))
        self.label_14.setText(_translate("MainWindow", "Gap penalization"))
        self.label_10.setText(_translate("MainWindow", "Gap:"))
        self.label_15.setText(_translate("MainWindow", "G:"))
        self.label_16.setText(_translate("MainWindow", "L:"))
        item = self.substitution_matrix.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "A"))
        item = self.substitution_matrix.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "C"))
        item = self.substitution_matrix.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "G"))
        item = self.substitution_matrix.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "T"))
        item = self.substitution_matrix.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "A"))
        item = self.substitution_matrix.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "C"))
        item = self.substitution_matrix.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "G"))
        item = self.substitution_matrix.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "T"))
        __sortingEnabled = self.substitution_matrix.isSortingEnabled()
        self.substitution_matrix.setSortingEnabled(False)
        item = self.substitution_matrix.item(0, 0)
        item.setText(_translate("MainWindow", "2"))
        item = self.substitution_matrix.item(0, 1)
        item.setText(_translate("MainWindow", "-7"))
        item = self.substitution_matrix.item(0, 2)
        item.setText(_translate("MainWindow", "-5"))
        item = self.substitution_matrix.item(0, 3)
        item.setText(_translate("MainWindow", "-7"))
        item = self.substitution_matrix.item(1, 0)
        item.setText(_translate("MainWindow", "-7"))
        item = self.substitution_matrix.item(1, 1)
        item.setText(_translate("MainWindow", "2"))
        item = self.substitution_matrix.item(1, 2)
        item.setText(_translate("MainWindow", "7"))
        item = self.substitution_matrix.item(1, 3)
        item.setText(_translate("MainWindow", "-5"))
        item = self.substitution_matrix.item(2, 0)
        item.setText(_translate("MainWindow", "-5"))
        item = self.substitution_matrix.item(2, 1)
        item.setText(_translate("MainWindow", "-7"))
        item = self.substitution_matrix.item(2, 2)
        item.setText(_translate("MainWindow", "2"))
        item = self.substitution_matrix.item(2, 3)
        item.setText(_translate("MainWindow", "-7"))
        item = self.substitution_matrix.item(3, 0)
        item.setText(_translate("MainWindow", "-7"))
        item = self.substitution_matrix.item(3, 1)
        item.setText(_translate("MainWindow", "-5"))
        item = self.substitution_matrix.item(3, 2)
        item.setText(_translate("MainWindow", "-7"))
        item = self.substitution_matrix.item(3, 3)
        item.setText(_translate("MainWindow", "2"))
        self.substitution_matrix.setSortingEnabled(__sortingEnabled)
        self.label_7.setText(_translate("MainWindow", "Substitution matrix"))
        self.match_option_cbox.setItemText(0, _translate("MainWindow", "Local match without affine gaps penalty"))
        self.match_option_cbox.setItemText(1, _translate("MainWindow", "Local match with affine gaps penalty"))
        self.label_12.setText(_translate("MainWindow", "Path:"))
        self.matchModeTab.setTabText(self.matchModeTab.indexOf(self.tab), _translate("MainWindow", "Local Match"))
        self.label_17.setText(_translate("MainWindow", "Scoring"))
        self.label_18.setText(_translate("MainWindow", "Gap:"))
        self.label_19.setText(_translate("MainWindow", "Match:"))
        self.label_20.setText(_translate("MainWindow", "Mismatch:"))
        self.matchModeTab.setTabText(self.matchModeTab.indexOf(self.tab_2), _translate("MainWindow", "Global Match"))
        self.label_21.setText(_translate("MainWindow", "Scoring:"))
        self.label_22.setText(_translate("MainWindow", "Gap:"))
        self.label_23.setText(_translate("MainWindow", "Match:"))
        self.label_24.setText(_translate("MainWindow", "Mismatch:"))
        self.label_26.setText(_translate("MainWindow", "Filtering:"))
        self.label_27.setText(_translate("MainWindow", "Window:"))
        self.label_28.setText(_translate("MainWindow", "Error:"))
        self.matchModeTab.setTabText(self.matchModeTab.indexOf(self.tab_3), _translate("MainWindow", "DotPlot"))
        self.show_match_button.setText(_translate("MainWindow", "Show Match"))
        self.label_25.setText(_translate("MainWindow", "Statistics:"))

        self.open_file_button_1.clicked.connect(self.open_file1)
        self.open_file_button_2.clicked.connect(self.open_file2)
        self.show_match_button.clicked.connect(self.make_plot)
        self.search_1.clicked.connect(self.search_by_id1)
        self.search_2.clicked.connect(self.search_by_id2)
        self.combobox_changed()
        self.combobox_2_changed()
        self.comboBox.currentTextChanged.connect(self.combobox_changed)
        self.comboBox_2.currentTextChanged.connect(self.combobox_2_changed)

    def combobox_changed(self):
        self.open_file_button_1.setDisabled(True)
        self.sequence_1_txt.setReadOnly(True)
        self.id_1_txt.setReadOnly(True)
        self.search_1.setDisabled(True)
        if self.comboBox.currentText().__eq__("User input"):
            self.sequence_1_txt.setReadOnly(False)
            self.id_1_txt.setReadOnly(False)
        elif self.comboBox.currentText().__eq__("From file"):
            self.open_file_button_1.setDisabled(False)
        else:
            self.search_1.setDisabled(False)
            self.id_1_txt.setReadOnly(False)

    def combobox_2_changed(self):
        self.open_file_button_2.setDisabled(True)
        self.sequence_2_txt.setReadOnly(True)
        self.id_2_txt.setReadOnly(True)
        self.search_2.setDisabled(True)
        if self.comboBox_2.currentText().__eq__("User input"):
            self.sequence_2_txt.setReadOnly(False)
            self.id_2_txt.setReadOnly(False)
        elif self.comboBox_2.currentText().__eq__("From file"):
            self.open_file_button_2.setDisabled(False)
        else:
            self.search_2.setDisabled(False)
            self.id_2_txt.setReadOnly(False)

    def open_file1(self):
        self.get_file_dir(1)

    def open_file2(self):
        self.get_file_dir(2)

    def make_plot(self):

        if self.comboBox.currentText().__eq__("User input"):
            content = '>' + self.id_1_txt.text() + '\n'
            content = content + self.sequence_1_txt.toPlainText()
            fastaList = FastaParser.parse_fasta(content)
            self.fasta1 = fastaList.__getitem__(0)
        if self.comboBox_2.currentText().__eq__("User input"):
            content = '>' + self.id_2_txt.text() + '\n'
            content = content + self.sequence_2_txt.toPlainText()
            fastaList = FastaParser.parse_fasta(content)
            self.fasta2 = fastaList.__getitem__(0)

        if (self.matchModeTab.currentIndex() == 0):
            self.localMatchPlot()
        if (self.matchModeTab.currentIndex() == 1):
            self.globalMatchPlot()
        if (self.matchModeTab.currentIndex() == 2):
            self.dotMatchPlot()

    def localMatchPlot(self):
        G = int(self.G_txt_lm.text())
        L = int(self.L_txt_lm.text())
        gap = int(self.gap_txt_lm.text())
        localMatch = LocalMatch(gap, G, L, self.sub_matrix_values())
        if self.match_option_cbox.currentText().__eq__("Local match without affine gaps penalty"):
            matrixes = localMatch.match(self.fasta1.get('sequence'), self.fasta2.get('sequence'), True)
        else:
            matrixes = localMatch.match(self.fasta1.get('sequence'), self.fasta2.get('sequence'), False)

        coordinates = localMatch.max_coordinates(matrixes[0])
        print(coordinates)

        self.path_nr_combobox.addItem(str(1))

        matrix = localMatch.compute_path(matrixes[1], matrixes[0], localMatch.sequence1, localMatch.sequence2,
                                         coordinates[1][int(self.path_nr_combobox.currentText()) - 1],
                                         coordinates[0][int(self.path_nr_combobox.currentText()) - 1])
        localMatch.show_plot(matrix, self.fasta1.get('id'), self.fasta2.get('id'))

        self.path_nr_combobox.clear()
        for i in range(0, len(coordinates[0])):
            self.path_nr_combobox.addItem(str(i + 1))

        self.statistics_txt.setPlainText(localMatch.get_stats())

    def dotMatchPlot(self):
        dotplot = DotPlot(int(self.mismatch_txt_dp.text()), int(self.match_txt_dp.text()), int(self.gap_txt_dp.text()))
        matrix = dotplot.make_dotplot(self.fasta1.get("sequence"), self.fasta2.get("sequence"))
        filteredDotplot = dotplot.filter_dotplot(matrix, int(self.error_txt_dp.text()), int(self.window_txt_dp.text()))
        dotplot.show_dotplot(filteredDotplot, self.fasta1.get("id"), self.fasta2.get("id"))
        print()

    def globalMatchPlot(self):

        globalMatch = GlobalMatch(int(self.mismatch_txt_gm.text()), int(self.match_txt_gm.text()),
                                  int(self.gap_txt_gm.text()))
        seq1 = self.fasta1.get('sequence')
        seq2 = self.fasta2.get('sequence')
        matrix = globalMatch.sequence_match(seq1, seq2)
        pathMatrix = globalMatch.mark_path(matrix[0], matrix[1], seq1, seq2)
        globalMatch.show_plot(pathMatrix, self.id_1_txt.text(), self.id_2_txt.text())
        self.statistics_txt.setPlainText(globalMatch.get_stats())

    def search_by_id1(self):
        self.search_by_id(1)

    def search_by_id2(self):
        self.search_by_id(2)



    def search_by_id(self, number):
        if number == 1:
            id = self.id_1_txt.text()
            content = FastaReader.fasta_from_url(id)
            fastaList = FastaParser.parse_fasta(content)
            self.fasta1 = fastaList.__getitem__(0)
            self.id_1_txt.setText(self.fasta1.get("id"))
            self.sequence_1_txt.setPlainText(self.fasta1.get("sequence"))

        else:
            id = self.id_2_txt.text()
            content = FastaReader.fasta_from_url(id)
            fastaList = FastaParser.parse_fasta(content)
            self.fasta2 = fastaList.__getitem__(0)
            self.id_2_txt.setText(self.fasta2.get("id"))
            self.sequence_2_txt.setPlainText(self.fasta2.get("sequence"))

    def get_file_dir(self, seq_number):
        options = QFileDialog.Options()
        options |= QFileDialog.DontUseNativeDialog
        fileName, _ = QFileDialog.getOpenFileName(None, "", "", "Text Files (*.txt *.fasta)",
                                                  options=options)
        if fileName != '':
            content = FastaReader.fasta_from_file(fileName)
            fastaList = FastaParser.parse_fasta(content)
            fasta = fastaList.__getitem__(0)
            id = fasta.get("id")
            sequence = fasta.get("sequence")
            if seq_number == 1:
                self.fasta1 = fasta
                self.id_1_txt.setText(id)
                self.sequence_1_txt.setPlainText(sequence)
            else:
                self.fasta2 = fasta
                self.id_2_txt.setText(id)
                self.sequence_2_txt.setPlainText(sequence)
        else:
            print("wrong file directory choosen")

    def sub_matrix_values(self):
        model = self.substitution_matrix.model()
        data = []
        i = 0
        data.append([])
        data[0].append('#')
        for j in range(model.columnCount()):
            data[0].append(self.substitution_matrix.verticalHeaderItem(j).text())
        for row in range(model.rowCount()):
            data.append([])
            i += 1
            data[i].append(data[0][i])
            for column in range(model.columnCount()):
                index = model.index(row, column)
                data[row + 1].append(int(model.data(index)))
        return data


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
